[package]
name = "mhstatus"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = true
strip = true

[lints.rust]
rust_2018_idioms = "deny"
unsafe_code = "forbid"
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[dependencies]
async-proto = "0.26"
base64 = "0.22.1"
clap = { version = "4.5.41", features = ["derive"] }
collect-mac = "0.1.0"
derivative = "2.2.0"
dir-lock = "0.5"
directories = "6.0.0"
futures = "0.3.31"
gix = "0.73"
hmac = "0.12.1"
itermore = { version = "0.8", features = ["array_chunks"] }
itertools = "0.14.0"
lazy-regex = "3.4.1"
log-lock = { git = "https://github.com/fenhl/log-lock" }
mimalloc = "0.1.46"
rocket = { version = "0.5.1", features = ["secrets"] }
rocket-util = { git = "https://github.com/fenhl/rocket-util" }
rocket_ws = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { package = "serde_json_path_to_error", version = "0.1" }
sha2 = "0.10.8"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["net", "process", "sync", "time"] }
url = "2.5.4"
wheel = { git = "https://github.com/fenhl/wheel", features = ["rocket", "serde_json"] }
which = "8"

[target."cfg(unix)".dependencies]
xdg = "3"

[build-dependencies]
gix = "0.73"
itertools = "0.14.0"
