[package]
name = "mhstatus"
version = "0.1.0"
edition = "2024"
rust-version = "1.91" # nixpkgs stable

[profile.release]
codegen-units = 1
lto = true
strip = true

[lints.rust]
rust_2018_idioms = "deny"
unsafe_code = "forbid"
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[build-dependencies]
gix = "0.81"
itertools = "0.14"

[dependencies]
async-proto = "0.26"
base64 = "0.22"
chrono = { version = "0.4", default-features = false }
chrono-tz = "0.10"
clap = { version = "4", features = ["derive"] }
collect-mac = "0.1"
derivative = "2"
dir-lock = "0.5"
directories = "6"
futures = "0.3"
gix = "0.81"
hmac = "0.13"
itermore = { version = "0.8", features = ["array_chunks"] }
itertools = "0.14"
lazy-regex = "3"
log-lock = { git = "https://github.com/fenhl/log-lock" }
mimalloc = "0.1"
rocket = { git = "https://github.com/fenhl/Rocket", branch = "forms", features = ["secrets"] }
rocket-util = { git = "https://github.com/fenhl/rocket-util", branch = "forms" }
rocket_ws = { git = "https://github.com/fenhl/Rocket", branch = "forms" }
serde = { version = "1", features = ["derive"] }
serde_json = { package = "serde_json_path_to_error", version = "0.1" }
sha2 = "0.11"
sqlx = { version = "0.8", default-features = false, features = ["chrono", "macros", "postgres", "runtime-tokio", "tls-rustls-ring-webpki"] }
thiserror = "2"
tokio = { version = "1", features = ["net", "process", "sync", "time"] }
url = "2"
wheel = { git = "https://github.com/fenhl/wheel", branch = "rocket-forms", features = ["night", "rocket", "serde_json"] }
which = "8"

[target."cfg(unix)".dependencies]
xdg = "3"
